"""empty message

Revision ID: 2536ab72c028
Revises: b904445d583
Create Date: 2016-12-15 17:37:14.869772

"""

# revision identifiers, used by Alembic.
revision = '2536ab72c028'
down_revision = 'b904445d583'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
